Traceback (most recent call last):
  File "pref_master_file.py", line 73, in <module>
    main_as_fun(model_name=job_model_names[job_idx], train_seq_part = job_seq_parts[job_idx], n_simulation_sequences_train = job_n_sim_seqs[job_idx], n_human_epochs_train = job_n_human_epochs[job_idx], run_idx=job_run_idxs[job_idx])
  File "/home/erussek/projects/RNNs/main_as_fun.py", line 108, in main_as_fun
    simulation_loss_results, human_loss_results, train_sequence_number,human_sequence_number, simulation_sequence_number, model = train_on_simulation_then_human_with_intermediate_tests(model,train_data_sim, train_data_human,test_data_sim,test_data_human,criterion,optimizer,device,batch_size,n_simulation_sequences_train, n_human_epochs_train, n_sequences_test, gen_data_func)
  File "/home/erussek/projects/RNNs/train_and_test_funs.py", line 148, in train_on_simulation_then_human_with_intermediate_tests
    for epoch_idx in range(n_human_epochs_train):
TypeError: 'float' object cannot be interpreted as an integer
