[32m[I 2022-06-22 16:09:32,278][0m A new study created in memory with name: no-name-08dd0202-949e-454a-816b-6aaa5d2604af[0m
/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/optuna/distributions.py:560: UserWarning: The distribution is specified by [2, 200] and step=5, but the range is not divisible by `step`. It will be replaced by [2, 197].
  warnings.warn(
[33m[W 2022-06-22 16:09:33,449][0m Trial 0 failed because of the following error: RuntimeError('Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)')[0m
Traceback (most recent call last):
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "predict_sim_find_optimal_params.py", line 357, in <lambda>
    this_obj = lambda trial: objective(trial, train_data_sim, test_data_sim, train_setting)
  File "predict_sim_find_optimal_params.py", line 332, in objective
    model_LSTM, loss = train_and_test(model, train_data_sim, test_data_sim, criterion, optimizer, device, batch_size, n_total_seq, data_func, model_name='LSTM')
  File "predict_sim_find_optimal_params.py", line 270, in train_and_test
    output = model(data)  # Step
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "predict_sim_find_optimal_params.py", line 210, in forward
    ha = self.input_hidden(x)
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)
train_setting: 2
0
Traceback (most recent call last):
  File "predict_sim_find_optimal_params.py", line 359, in <module>
    study.optimize(this_obj, n_trials=n_optuna_trials)
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/optuna/study/study.py", line 400, in optimize
    _optimize(
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/optuna/study/_optimize.py", line 264, in _run_trial
    raise func_err
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "predict_sim_find_optimal_params.py", line 357, in <lambda>
    this_obj = lambda trial: objective(trial, train_data_sim, test_data_sim, train_setting)
  File "predict_sim_find_optimal_params.py", line 332, in objective
    model_LSTM, loss = train_and_test(model, train_data_sim, test_data_sim, criterion, optimizer, device, batch_size, n_total_seq, data_func, model_name='LSTM')
  File "predict_sim_find_optimal_params.py", line 270, in train_and_test
    output = model(data)  # Step 
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "predict_sim_find_optimal_params.py", line 210, in forward
    ha = self.input_hidden(x)
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/erussek/.conda/envs/pDL/lib/python3.8/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)
